// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlDF_01pmzMzlN4CzRNrrW2S_8dmmJ_Pw',
    appId: '1:149013031229:web:33f9ab745a4863d82b3d54',
    messagingSenderId: '149013031229',
    projectId: 'helmetdetectfyp',
    authDomain: 'helmetdetectfyp.firebaseapp.com',
    storageBucket: 'helmetdetectfyp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL3iAvueqN5S9Euy6a9kQpTXvUnsp9lUo',
    appId: '1:149013031229:android:684e8d8a8edd3a6c2b3d54',
    messagingSenderId: '149013031229',
    projectId: 'helmetdetectfyp',
    storageBucket: 'helmetdetectfyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfzkFz9KhLWgyMgcmsHH2UB3b4InHN4gw',
    appId: '1:149013031229:ios:35c22c93472182ac2b3d54',
    messagingSenderId: '149013031229',
    projectId: 'helmetdetectfyp',
    storageBucket: 'helmetdetectfyp.appspot.com',
    iosBundleId: 'com.example.helmetdetect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfzkFz9KhLWgyMgcmsHH2UB3b4InHN4gw',
    appId: '1:149013031229:ios:fe69d69080a093c52b3d54',
    messagingSenderId: '149013031229',
    projectId: 'helmetdetectfyp',
    storageBucket: 'helmetdetectfyp.appspot.com',
    iosBundleId: 'com.example.helmetdetect.RunnerTests',
  );
}
